import type { Metadata } from 'next';
import './globals.css';
import { pixeled } from './styles/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${pixeled.className} bg-black text-white`}>{children}</body>
    </html>
  );
}
